# .github/workflows/ci.yml

name: FastAPI Calculator CI

# This tells GitHub to run the workflow on every 'push'
# to your 'main' branch, or on any pull request.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    # This job will run on a fresh Ubuntu machine
    runs-on: ubuntu-latest

    steps:
    # 1. Checks out your repository's code
    - name: Check out code
      uses: actions/checkout@v4

    # 2. Sets up the Python version
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    # 3. Installs all your project's dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # 4. Installs the OS-level dependencies for Playwright
    # This is the 'sudo' command that you ran locally
    - name: Install Playwright OS dependencies
      run: sudo playwright install-deps

    # 5. Installs the Playwright browsers (Chromium, etc.)
    - name: Install Playwright browsers
      run: playwright install

    # 6. Runs your fast tests (unit and integration)
    - name: Run Unit and Integration Tests
      run: pytest tests/test_unit.py tests/test_integration.py

    # 7. Runs your E2E tests (this is the complex part)
    - name: Run E2E Tests
      run: |
        # Start the FastAPI server in the background
        # We use port 8008 just to be safe
        uvicorn app.main:app --host 0.0.0.0 --port 8008 &
        
        # Wait for 5 seconds to give the server time to start
        sleep 5
        
        # Run the E2E tests against the server
        pytest tests/test_e2E.py --base-url http://127.0.0.1:8008