name: FastAPI Calculator CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # FIX: Removed 'sudo'
    # This now uses the correct Python, and the command
    # will handle its own admin permissions.
    - name: Install Playwright OS dependencies
      run: python -m playwright install-deps

    - name: Install Playwright browsers
      run: playwright install

    - name: Run Unit and Integration Tests
      run: pytest tests/test_unit.py tests/test_integration.py

    - name: Run E2E Tests
      run: |
        uvicorn app.main:app --host 0.0.0.0 --port 8008 &
        sleep 5
        pytest tests/test_e2e.py --base-url http://127.0.0.1:8008